# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /SYSTEMS/IOT/Roverdyn/PROJ_TCP_DB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /SYSTEMS/IOT/Roverdyn/PROJ_TCP_DB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /SYSTEMS/IOT/Roverdyn/PROJ_TCP_DB/CMakeFiles /SYSTEMS/IOT/Roverdyn/PROJ_TCP_DB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /SYSTEMS/IOT/Roverdyn/PROJ_TCP_DB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SOLARMY_APP

# Build rule for target.
SOLARMY_APP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SOLARMY_APP
.PHONY : SOLARMY_APP

# fast build rule for target.
SOLARMY_APP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/build
.PHONY : SOLARMY_APP/fast

MySQLService.o: MySQLService.cpp.o
.PHONY : MySQLService.o

# target to build an object file
MySQLService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/MySQLService.cpp.o
.PHONY : MySQLService.cpp.o

MySQLService.i: MySQLService.cpp.i
.PHONY : MySQLService.i

# target to preprocess a source file
MySQLService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/MySQLService.cpp.i
.PHONY : MySQLService.cpp.i

MySQLService.s: MySQLService.cpp.s
.PHONY : MySQLService.s

# target to generate assembly for a file
MySQLService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/MySQLService.cpp.s
.PHONY : MySQLService.cpp.s

TCPService.o: TCPService.cpp.o
.PHONY : TCPService.o

# target to build an object file
TCPService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/TCPService.cpp.o
.PHONY : TCPService.cpp.o

TCPService.i: TCPService.cpp.i
.PHONY : TCPService.i

# target to preprocess a source file
TCPService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/TCPService.cpp.i
.PHONY : TCPService.cpp.i

TCPService.s: TCPService.cpp.s
.PHONY : TCPService.s

# target to generate assembly for a file
TCPService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/TCPService.cpp.s
.PHONY : TCPService.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLARMY_APP.dir/build.make CMakeFiles/SOLARMY_APP.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SOLARMY_APP"
	@echo "... MySQLService.o"
	@echo "... MySQLService.i"
	@echo "... MySQLService.s"
	@echo "... TCPService.o"
	@echo "... TCPService.i"
	@echo "... TCPService.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

